version: '3.7'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # MinIO API port
      - "9001:9001"  # MinIO Console port
    volumes:
      - ./minio-data:/data  # Local directory for persistent storage
    environment:
      - MINIO_ROOT_USER=minioadmin  # Default root user
      - MINIO_ROOT_PASSWORD=minioadmin  # Default root password
    command: server /data --console-address ":9001"  # Start MinIO server
    restart: unless-stopped  # Automatically restart the container unless stopped